#!/bin/sh
###################\
exec tclsh "$0" "$@"

if [catch { exec uname } Stat(S)] {
	set Stat(S) "W"
} elseif [regexp -nocase "linux" $Stat(S)] {
	set Stat(S) "L"
} elseif [regexp -nocase "cygwin" $Stat(S)] {
	set Stat(S) "C"
} else {
	set Stat(S) "W"
}

# arguments: private bin directory + path to container directory + rtag
set bin [lindex $argv 0]
set vpa [lindex $argv 1]
set rta [lindex $argv 2]

if { $bin == "" } {
	set bin "bin"
}

if { $vpa == "" } {
	set vpa "SOFTWARE"
}

if { $rta == "" } {
	set rta "0"
}

puts "Compiling maker, bin=$bin, container=$vpa, rtag=$rta ..."

cd SOURCES

exec g++ -o maker maker.cc

if { $Stat(S) != "L" } {
	# Cygwin/Windows
	set exf "maker.exe"
} else {
	set exf "maker"
}

exec strip $exf

puts "Running maker for mks ..."
set out [exec [auto_execok ./maker] -b -r $rta << \
	"none\n\n\n25\n\n\nlocalhost\n4442\nmks\n$bin\ny\nn\n\n\n"]
puts $out

puts "Running maker for vuee ..."
set out [exec [auto_execok ./maker] -b -r $rta << \
	"none\n\n\n25\n$vpa/VUEE/PICOS\n\n$vpa/PICOS/Apps/DataLib\n\nlocalhost\n4442\nvuee\n$bin\ny\nn\n\n\n"]
puts $out
