#!/bin/sh
###################\
exec tclsh "$0" "$@"
#
# Creates an installable version of elvis; must be run separately under Cygwin
# and Linux; uses the system's elvis installation, so make sure it is up to
# date
#

set ST(SYS) "W"
set ST(VER) 32

###############################################################################
# Determine the system type ###################################################
###############################################################################

if [catch { exec uname -a } ST(SYS)] {

	puts "cannot determine system type,\
			assuming (stupidly) $ST(SYS) $ST(VER)"
} else {

	if { [string first "x86_64" $ST(SYS)] > 0 } {
		set ST(VER) 64
	}

	if [regexp -nocase "linux" $ST(SYS)] {
		set ST(SYS) "L"
	} elseif [regexp -nocase "cygwin" $ST(SYS)] {
		set ST(SYS) "C"
	} else {
		set ST(SYS) "W"
	}
}

# current directory
set WD [pwd]

proc abort { msg } {

	puts stderr $msg
	exit 99
}

set BINFILES { 
		/usr/bin/elvis
		/usr/bin/elvtags
}

set SHAREDFILES {
		/usr/share/elvis
}

###############################################################################

if { $ST(SYS) == "L" } {
	set TD [file join $WD "ELVIS" "LINUX"]
} else {
	set TD [file join $WD "ELVIS" "CYGWIN"]
	set b ""
	foreach f $BINFILES {
		lappend b $f.exe
	}
	set BINFILES $b
}

puts "Target directory is $TD"

if { $ST(VER) == 64 } {
	set BD "64"
} else {
	set BD ""
}

set BD [file join $TD "BIN$BD"]
set SD [file join $TD "SHARED"]

catch { file delete -force -- $BD }
catch { file delete -force -- $SD }

if { [catch { file mkdir $TD } ] || [catch { file mkdir $BD } ] ||
     [catch { file mkdir $SD } ] } {
	abort "Cannot create one of target directories"
}

puts "Copying to $BD ..."

foreach b $BINFILES {
	puts "Copying $b"
	if [catch { file copy -force $b $BD } err] {
		abort "Cannot copy $b to $BD: $err"
	}
}

puts "Copying to $SD ..."

foreach b $SHAREDFILES {
	puts "Copying $b"
	if [catch { file copy -force $b $SD } err] {
		abort "Cannot copy $b to $SD: $err"
	}
}

puts "ALL DONE"
