#!/bin/sh
###################\
exec tclsh "$0" "$@"
#
# Creates a release version in picospack.tgz with the .git directories stripped
# off and everything cleaned up
#

proc cygfix { } { catch { exec ls [pwd] } }

cygfix

set tfn "/tmp/picrelease_[pid]_[clock seconds]"
exec mkdir $tfn
set cwd [pwd]
set expd [lindex $argv 0]
if { $expd != "" } {
	# export data specified, produce export version of PICOS
	puts "exporting PICOS ..."
	exec sh Scripts/pxport $expd $cwd "$tfn/PICOS"
} else {
	puts "copying PICOS ..."
	exec cp -r ../PICOS "$tfn/"
}
cd ..
puts "copying SIDE VUEE PIP ..."
exec cp -r SIDE VUEE PIP "$tfn/"
cd $tfn
cd PICOS
puts "cleaning up PICOS ..."
exec rm -rf .git
exec sh ./cleanup
cd Apps
puts "cleaning up PICOS Apps ..."
exec sh ./cleanup -p
cd ..
cd ../SIDE
puts "cleaning up SIDE ..."
exec rm -rf .git
exec sh ./cleanup
cd ../VUEE
puts "cleaning up VUEE ..."
exec rm -rf .git
exec sh ./cleanup
cd ../PIP
puts "cleaning up PIP ..."
exec rm -rf .git
exec sh ./cleanup
cd ..
puts "packaging ..."
exec tar cvf - PICOS SIDE VUEE PIP | gzip -9 > [file join $cwd picospack.tgz] \
	2>[file join $tfn serr]
cd $cwd
puts "cleaning up ..."
exec rm -rf $tfn
