#!/bin/sh
#
# Strips the sources for a library-only deployment of VUEE/SMURPH
# (not for normal use)
#
./cleanup
rm -rf .git
cd Examples
rm -rf A* B* E* O* R* S* T* W*
cd IncLib
rm -rf a* c* d* e* f* h* l* m* p* rf* rp* s* t* u*
cd ../..
##################################################
rm -rf MANUAL
cd SOURCES
rm -rf STANDALONE DSD MONITOR NWEB
cd KERNEL
mv depend_precomp.txt depend.txt
rm -rf *.cc
cd ../LIB
rm -rf Makefile *.cc *.c ifranlib
cd ../..
##########################################################
rm -rf INSTALL.txt README.txt scopy* strip*
mv deploy_nosource deploy
##########################################################
