#!/bin/sh
g++ -o maker maker.cc
strip maker
if [ -d "$HOME/bin" ]
then
	bindir="bin"
else
if [ -d "$HOME/BIN" ]
then
	bindir="BIN"
else
	echo "Your need a subdirectory named bin or BIN in your home directory!"
	exit 1
fi
fi
./maker <<END1
none


25


localhost
4442
mks
$bindir
y
n


END1
./maker <<END2
none


25
SOFTWARE/VUEE/PICOS

SOFTWARE/PICOS/Apps/DataLib

localhost
4442
vuee
$bindir
y
n


END2
