#!/bin/sh
g++ -o maker maker.cc
strip maker
if [ -d "$HOME/bin" ]
then
	bindir="bin"
else
if [ -d "$HOME/BIN" ]
then
	bindir="BIN"
else
	echo "Your need a subdirectory named bin or BIN in your home directory!"
	echo "That directory should be present in your PATH."
	exit 1
fi
fi
./maker <<ENDINPUT
none


25


localhost
4442
mks
$bindir
y
n


ENDINPUT
