#!/usr/bin/tclsh
#
#	Copyright 1995-2020 Pawel Gburzynski
#
#	This file is part of SMURPH/SIDE.
#
#	SMURPH/SIDE is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#	SMURPH/SIDE is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with SMURPH/SIDE. If not, see <https://www.gnu.org/licenses/>.
#

set CONV	[expr 299792458.0 * 10.0]

proc toetu { arg } {

	global CONV

	puts [format %8.6f [expr $arg / $CONV]]
}

proc toitu { arg } {

	global CONV

	puts [format %1.0f [expr $arg * $CONV]]
}

while 1 {

	set lin [string trim [gets stdin]]
	if { $lin == "" } {
		continue
	}
	if { [string first "." $lin] >= 0 } {
		set etu 1
	} else {
		append lin "."
		set etu 0
	}

	if [catch { expr $lin } arg] {
		puts "Illegal number"
		continue
	}

	if $etu {
		toitu $arg
	} else {
		toetu $arg
	}
}
