# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded autoconnect 1.0 [list source [file join $dir autoconnect.tcl]]
package ifneeded boss 1.0 [list source [file join $dir boss.tcl]]
package ifneeded fesc 1.0 [list source [file join $dir fesc.tcl]]
package ifneeded log 1.0 [list source [file join $dir log.tcl]]
package ifneeded noss 1.0 [list source [file join $dir noss.tcl]]
package ifneeded oep 1.0 [list source [file join $dir oep.tcl]]
package ifneeded oss_u 1.0 [list source [file join $dir oss_u.tcl]]
package ifneeded oss_u_xrs 1.0 [list source [file join $dir oss_u_xrs.tcl]]
package ifneeded sdb 1.0 [list source [file join $dir sdb.tcl]]
package ifneeded snippets 1.0 [list source [file join $dir snippets.tcl]]
package ifneeded tooltips 1.0 [list source [file join $dir tooltips.tcl]]
package ifneeded uartpoll 1.0 [list source [file join $dir uartpoll.tcl]]
package ifneeded unames 1.0 [list source [file join $dir unames.tcl]]
package ifneeded vuart 1.0 [list source [file join $dir vuart.tcl]]
package ifneeded xml 1.0 [list source [file join $dir xml.tcl]]
