/* ==================================================================== */
/* Copyright (C) Olsonet Communications, 2002 - 2004.                   */
/* All rights reserved.                                                 */
/* ==================================================================== */
// Common for Tags and Pegs apps
msg_getTag, msg_getTagAck, msg_setTag, msg_setTagAck, msg_rpc, msg_pong
