#!/bin/sh
#
#	Copyright 2002-2020 (C) Olsonet Communications Corporation
#	Programmed by Pawel Gburzynski & Wlodek Olesinski
#	All rights reserved
#
#	This file is part of the PICOS platform
#
#
##########################\
exec tclsh "$0" "$@"

#
# Traverse the file tree and fix permissions, so that everything looks nice,
# e.g., after pushing the set back and forth through different incompatible
# filesystems.
#

set Extensions { ".exe" ".out" ".tcl" ".sh" }

set Headers ""

lappend Headers [binary format cccc 0x4d 0x5a 0x90 0x00]
lappend Headers [binary format cccc 0x7f 0x45 0x4c 0x46]
lappend Headers [binary format cccc 0x23 0x21 0x2f 0x62]
lappend Headers [binary format cccc 0x23 0x21 0x2f 0x75]

proc calc_mode { fn } {
#
# Determine mode
#
	global Extensions Headers

	set ext [string tolower [file extension $fn]]

	foreach pat $Extensions {

		if { $pat == $ext } {
			return 755
		}
	}

	# content
	if [catch { open $fn "r" } fd] {
		# cannot open
		if [catch { exec chmod -f 444 $fn } err] {
			puts stderr "cannot chmod 444 $d: $err"
			exit 99
		}
		if [catch { open $fn "r" } fd] {
			return 644
		}
	}

	fconfigure $fd -encoding binary

	set hdr [read $fd 4]

	catch { close $fd }

	foreach pat $Headers {
		if { $pat == $hdr } {
			return 755
		}
	}

	return 644
}

proc do_it { path } {
#
# Handles the current directory
#
	if [catch { glob -nocomplain * } flist] {
		puts stderr "cannot list directory: $flist"
		exit 99
	}

	if [catch { glob -types hidden -nocomplain * } hlist] {
		puts stderr "cannot list directory: $hlist"
		exit 99
	}

	set flist [concat $flist $hlist]

	foreach d $flist {
		if { $d == "." || $d == ".." } {
			continue
		}
		set npa [file join $path $d]
		if [file isdirectory $d] {
			# change permissions
			if [catch { exec chmod -f 755 $d } err] {
				puts stderr "cannot chmod 775 $d: $err"
				exit 99
			}
			# traverse
			if [catch { file lstat $d vv } err] {
				puts stderr "cannot stat $d: $err"
				exit 99
			}
			if { $vv(type) != "directory" } {
				continue
			}
			array unset vv
			set c [pwd]
			puts "D: $npa"
			if ![catch { cd [file join $c $d] } ] {
				# dout $c
				do_it $npa
				cd $c
			}
			continue
		}

		if ![file isfile $d] {
			# ignore links, if any
			puts "L: $npa"
			continue
		}

		# a regular file
		puts "F: $npa"
		set md [calc_mode $d]
		if [catch { exec chmod -f $md $d } err] {
			puts stderr "cannot chmod $md $d: $err"
			exit 99
		}
	}
}	

do_it ""
