#ifndef _SMARTRF_SETTINGS_H_
#define _SMARTRF_SETTINGS_H_

// Adapted by PG from the file generated by smartrf studio


//*********************************************************************************
// Generated by SmartRF Studio version 2.5.1 (build #4)
// Tested for SimpleLink SDK version: CC13x0 SDK 1.0.xx
// Device: CC1350 Rev. 2.1
// 
//*********************************************************************************

#if 0
#ifdef DEVICE_FAMILY 
    #undef DEVICE_FAMILY_PATH 
    #define DEVICE_FAMILY_PATH(x) <ti/devices/DEVICE_FAMILY/x> 
#else 
    #error "You must define DEVICE_FAMILY at the project level as one of cc26x0, cc26x0r2, cc13x0, etc." 
#endif 
#endif

#define DEVICE_FAMILY_PATH(x) <x> 

#include <driverlib/rf_mailbox.h>
#include <driverlib/rf_common_cmd.h>
#include <driverlib/rf_prop_cmd.h>
// #include <ti/drivers/rf/RF.h>

// ============================================================================

// Make sure options are visible
#include "kernel.h"
#include "cc1350.h"

// ============================================================================

#if 0
// TI-RTOS RF Mode Object, not neeeded
extern RF_Mode RF_prop;
#endif

// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_PROP_TX_t RF_cmdPropTx;
extern rfc_CMD_PROP_RX_t RF_cmdPropRx;

#endif // _SMARTRF_SETTINGS_H_
