#!/bin/sh
../Scripts/cleanapp
if [ -d TESTS ]
then
	cd TESTS
	../../Scripts/cleanapp
	cd ..
fi

if [ -d SFU ]
then
	cd SFU
	../../Scripts/cleanapp
	cd ..
fi

if [ -d VUEE ]
then
	cd VUEE
	../../Scripts/cleanapp
if [ -d SEAWOLF ]
then
	cd SEAWOLF
	../../../Scripts/cleanapp
	cd ..
fi
	cd ..
fi

if [ -d ECOPROJECT ]
then
	cd ECOPROJECT
	../../Scripts/cleanapp
	cd ..
fi

if [ -d LIB_EXAMPLE ]
then
	cd LIB_EXAMPLE
	../../Scripts/cleanapp
	cd ..
fi
if [ -d SEAWOLF ]
then
	cd SEAWOLF
	../../Scripts/cleanapp
	cd ..
fi
