#!/bin/bash
#
#	Copyright 2002-2020 (C) Olsonet Communications Corporation
#	Programmed by Pawel Gburzynski & Wlodek Olesinski
#	All rights reserved
#
#	This file is part of the PICOS platform
#
#
if [ "x$1" = "xall" ] ||  [ "x$1" = "x-all" ] || [ "x$1" = "x--all" ]; then
pushd ../PIP
echo "Cleaning PIP"
./cleanup
popd
pushd ../VUEE
echo "Cleaning VUEE"
./cleanup
popd
pushd ../SIDE
echo "Cleaning SIDE"
./cleanup
popd
echo "Cleaning PICOS"
elif [ "x$1" != "x" ]; then
echo "Usage: cleanup [-all]"
exit 99
fi
cd Apps
./cleanup
cd ..
# remove libraries and their make accessories
rm -rf PicOS/*/BOARDS/*/libpicos.a
rm -rf PicOS/*/BOARDS/*/Makefile
rm -rf PicOS/*/BOARDS/*/KTMP
./Scripts/permissions
