#!/bin/sh
#
#	Copyright 2002-2020 (C) Olsonet Communications Corporation
#	Programmed by Pawel Gburzynski & Wlodek Olesinski
#	All rights reserved
#
#	This file is part of the PICOS platform
#
#
./rmlinks
ln -s ../../PICOS/PicOS/PLibs/Sensors/tmp007.h tmp007.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/sca3100.h sca3100.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/mpu9250.h mpu9250.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/obmicrophone.h obmicrophone.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/hdc1000.h hdc1000.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/opt3001.h opt3001.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/bmp280.h bmp280.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/bmp085.h bmp085.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/bma250.h bma250.h
ln -s ../../PICOS/PicOS/PLibs/Sensors/as3932.h as3932.h
ln -s ../../PICOS/PicOS/modsyms.h modsyms.h
ln -s ../../PICOS/PicOS/PLibs/Misc/dbgtrc.h dbgtrc.h
ln -s ../../PICOS/PicOS/PLibs/VNetI/tcv.c tcv.cc
ln -s ../../PICOS/PicOS/PLibs/VNetI/tcv.h .
ln -s ../../PICOS/PicOS/PLibs/VNetI/tcv_defs.h .
ln -s ../../PICOS/PicOS/PLibs/VNetI/tcv_node_data.h .
ln -s ../../PICOS/PicOS/PLibs/VNetI/tcvphys.h .
ln -s ../../PICOS/PicOS/PLibs/VNetI/tcvplug.h .
ln -s ../../PICOS/PicOS/PLibs/RF/rfleds.h .
ln -s ../../PICOS/PicOS/PLibs/Serial/ualeds.h .
ln -s ../../PICOS/PicOS/PLibs/LCD/lcdg_n6100p.c lcdg_n6100p.cc
ln -s ../../PICOS/PicOS/PLibs/Misc/encrypt.h .
ln -s ../../PICOS/PicOS/PLibs/Misc/encrypt.c encrypt.cc
ln -s ../../PICOS/PicOS/PLibs/Misc/checksum.c checksum.cc
ln -s ../../PICOS/PicOS/PLibs/RF/cc1100.h .
ln -s ../../PICOS/PicOS/CC13XX/cc1350.h .
####################################### for completeness (PicOS side)
ln -s board.h form.h
ln -s board.h ser.h
ln -s board.h serf.h
ln -s board.h storage.h
ln -s board.h net.h
ln -s board.h lcdg_n6100p.h
ln -s board.h phys_uart.h
ln -s board.h pins.h
ln -s board.h phys_cc1100.h
ln -s board.h phys_cc1350.h
ln -s board.h phys_cc2420.h
ln -s board.h pinopts.h
ln -s board.h rtc_s35390.h
ln -s board.h rtc_cc430.h
ln -s board.h sensors.h
ln -s board.h actuators.h
ln -s board.h hold.h
ln -s board.h cc2420.h
