#!/bin/sh
ln -sf ../../PICOS/PicOS/tcv.c tcv.cc
ln -sf ../../PICOS/PicOS/tcv.h .
ln -sf ../../PICOS/PicOS/tcv_node_data.h .
ln -sf ../../PICOS/PicOS/tcvphys.h .
ln -sf ../../PICOS/PicOS/tcvplug.h .
ln -sf ../../PICOS/PicOS/rfleds.h .
ln -sf ../../PICOS/PicOS/Libs/Lib/plug_null.h .
ln -sf ../../PICOS/PicOS/Libs/Lib/plug_null.c plug_null.cc
ln -sf ../../PICOS/PicOS/Libs/Lib/plug_null_node_data.h .
ln -sf ../../PICOS/PicOS/Libs/Lib/plug_null_node_data_init.h .
####################################### LibComms
ln -sf ../../PICOS/PicOS/Libs/LibComms/msg_tarp.h .
ln -sf ../../PICOS/PicOS/Libs/LibComms/net.c net.cc
ln -sf ../../PICOS/PicOS/Libs/LibComms/net_node_data.h .
ln -sf ../../PICOS/PicOS/Libs/LibComms/net_node_data_init.h .
ln -sf ../../PICOS/PicOS/Libs/LibComms/plug_tarp.c plug_tarp.cc
ln -sf ../../PICOS/PicOS/Libs/LibComms/plug_tarp.h .
ln -sf ../../PICOS/PicOS/Libs/LibComms/plug_tarp_node_data.h .
ln -sf ../../PICOS/PicOS/Libs/LibComms/plug_tarp_node_data_init.h .
ln -sf ../../PICOS/PicOS/Libs/LibComms/tarp.c tarp.cc
ln -sf ../../PICOS/PicOS/Libs/LibComms/tarp.h .
ln -sf ../../PICOS/PicOS/Libs/LibComms/tarp_node_data.h .
ln -sf ../../PICOS/PicOS/Libs/LibComms/tarp_node_data_init.h .

ln -sf ../../PICOS/PicOS/Libs/Lib/encrypt.h .
ln -sf ../../PICOS/PicOS/Libs/Lib/encrypt.c encrypt.cc
