#!/bin/sh
rm -f pinopts.h
rm -f phys_uart.h
rm -f net.h
rm -f pins.h
rm -f lcdg_n6100p.h
rm -f form.h
rm -f ser.h
rm -f serf.h
rm -f storage.h
rm -f phys_cc1100.h
#################################
rm -f tcv.cc
rm -f tcv.h
rm -f tcv_node_data.h
rm -f tcvphys.h
rm -f tcvplug.h
rm -f rfleds.h
rm -f ualeds.h
rm -f lcdg_n6100p.cc
rm -f plug_null.h
rm -f plug_null.cc
rm -f plug_null_node_data.h
rm -f plug_null_node_data_init.h
#################################
rm -f msg_tarp.h
rm -f net.cc
rm -f net_node_data.h
rm -f net_node_data_init.h
rm -f plug_tarp.cc
rm -f plug_tarp.h
rm -f plug_tarp_node_data.h
rm -f plug_tarp_node_data_init.h
rm -f tarp.cc
rm -f tarp.h
rm -f tarp_hooks.h
rm -f tarp_node_data.h
rm -f tarp_node_data_init.h

rm -f encrypt.h
rm -f encrypt.cc
rm -f checksum.cc

rm -f ab_data.h
rm -f ab.cc
rm -f abb.cc
rm -f ab_common.cc
rm -f ab_params.h
rm -f ab_modes.h
rm -f ab.h
rm -f abb.h

rm -f oep.cc
rm -f oep.h
rm -f oep_node_data.h
rm -f oep_node_data_init.h
rm -f oep_params.h
rm -f oep_types.h
rm -f oep_ee_types.h
rm -f oep_ee_node_data.h
rm -f oep_ee_node_data_init.h
rm -f oep_ee.cc
rm -f oep_ee.h

rm -f ee_ol.cc
rm -f ee_ol.h

rm -f lcdg_dispman.cc
rm -f lcdg_dispman.h
rm -f lcdg_dispman_node_data.h
rm -f lcdg_dispman_node_data_init.h
rm -f lcdg_dispman_params.h
rm -f lcdg_dispman_types.h
rm -f lcdg_images.cc
rm -f lcdg_images.h
rm -f lcdg_images_node_data.h
rm -f lcdg_images_node_data_init.h
rm -f lcdg_images_params.h
rm -f lcdg_images_types.h
