#!/bin/sh
rm -f tcv.cc
rm -f tcv.h
rm -f tcv_node_data.h
rm -f tcvphys.h
rm -f tcvplug.h
rm -f rfleds.h
rm -f plug_null.h
rm -f plug_null.cc
rm -f plug_null_node_data.h
rm -f plug_null_node_data_init.h
#################################
rm -f msg_tarp.h
rm -f net.cc
rm -f net.h
rm -f net_node_data.h
rm -f net_node_data_init.h
rm -f plug_tarp.cc
rm -f plug_tarp.h
rm -f plug_tarp_node_data.h
rm -f plug_tarp_node_data_init.h
rm -f tarp.cc
rm -f tarp.h
rm -f tarp_hooks.h
rm -f tarp_node_data.h
rm -f tarp_node_data_init.h

rm -f encrypt.h
rm -f encrypt.cc
