#ifndef __picos_stdattr_undef_h__
#define __picos_stdattr_undef_h__
// Created automatically, do not edit!!!
#undef __picos_stdattr_h__
#undef NODENAME
#undef release
#undef finish
#undef entropy
#undef min_backoff
#undef max_backoff
#undef backoff
#undef lbt_delay
#undef lbt_threshold
#undef phys_dm2200
#undef phys_cc1100
#undef rnd
#undef diag
#undef reset
#undef getpid
#undef seconds
#undef actsize
#undef delay
#undef when
#undef io
#undef encrypt
#undef decrypt
#undef leds
#undef fastblink
#undef vform
#undef vscan
#undef form
#undef scan
#undef ser_out
#undef ser_outb
#undef ser_in
#undef ser_outf
#undef ser_inf
#undef pin_read
#undef pin_write
#undef pin_read_adc
#undef pin_write_dac
#undef pmon_start_cnt
#undef pmon_stop_cnt
#undef pmon_set_cmp
#undef pmon_get_cnt
#undef pmon_get_cmp
#undef pmon_start_not
#undef pmon_stop_not
#undef pmon_get_state
#undef pmon_pending_not
#undef pmon_pending_cmp
#undef pmon_dec_cnt
#undef pmon_sub_cnt
#undef pmon_add_cmp
#undef ee_read
#undef ee_write
#undef ee_erase
#undef ee_sync
#undef if_write
#undef if_read
#undef if_erase
#undef net_opt
#undef net_qera
#undef net_init
#undef net_rx
#undef net_tx
#undef net_close
#undef getSpdCacheSize
#undef getDdCacheSize
#undef getDd
#undef getSpd
#undef getDdM
#undef getSpdM
#undef tcv_endp
#undef tcv_open
#undef tcv_close
#undef tcv_plug
#undef tcv_rnp
#undef tcv_qsize
#undef tcv_erase
#undef tcv_wnpu
#undef tcv_wnp
#undef tcv_read
#undef tcv_write
#undef tcv_drop
#undef tcv_left
#undef tcv_urgent
#undef tcv_isurgent
#undef tcv_control
#undef tcvp_control
#undef tcvp_assign
#undef tcvp_attach
#undef tcvp_clone
#undef tcvp_dispose
#undef tcvp_new
#undef tcvp_hook
#undef tcvp_unhook
#undef tcvp_settimer
#undef tcvp_cleartimer
#undef tcvp_length
#undef tcvphy_reg
#undef tcvphy_rcv
#undef tcvphy_get
#undef tcvphy_top
#undef tcvphy_end
#undef tcvphy_erase
#undef tcv_init
#undef tcv_dumpqueues
#undef net_id
#undef local_host
#undef master_host
#undef tarp_ctrl
#undef tr_offset
#undef msg_isBind
#undef msg_isTrace
#undef msg_isMaster
#undef msg_isNew
#undef msg_isClear
#undef set_master_chg
#endif
