#!/bin/sh
#
#	Copyright 2002-2020 (C) Olsonet Communications Corporation
#	Programmed by Pawel Gburzynski & Wlodek Olesinski
#	All rights reserved
#
#	This file is part of the PICOS platform
#
#
rm -rf KTMP KTMP_* VUEE_TMP Image* Makefile Makefile_* .gdbinit gdb.ini *.o side.* side */LIBRARY *.stackdump junk*
